services:
  telegram_bot_api:
    image: aiogram/telegram-bot-api:latest
    container_name: telegram-bot-api
    environment:
      TELEGRAM_API_ID: ${API_ID}
      TELEGRAM_API_HASH: ${API_HASH}
      TELEGRAM_LOCAL: "1"        # عبور از محدودیت ۵۰ مگابایت
    ports:
      - "8081:8081"
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    restart: unless-stopped

volumes:
  telegram-bot-api-data:
