FROM aiogram/telegram-bot-api:latest

# محل ذخیره‌سازی فایل‌ها را به /data تغییر بده
# (با Volume مشترک با ربات هماهنگ می‌شود)
CMD ["telegram-bot-api", "--local", "--dir=/data", "--http-port=8081"]

EXPOSE 8081
