services:
  telegram_bot_api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_ID: ${API_ID}
        API_HASH: ${API_HASH}
    image: telegram-bot-api
    container_name: telegram-bot-api
    env_file:
      - .env
    ports:
      - "8081:8081"
    volumes:
      - telegram-bot-api-data:/data
    restart: unless-stopped

volumes:
  telegram-bot-api-data:
